# Generated by Django 3.1.3 on 2020-11-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursesModel',
        ),
        migrations.RemoveField(
            model_name='studentfacultycourses',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='studentfacultycourses',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentparentrelation',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='studentparentrelation',
            name='student_id',
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='email',
            field=models.EmailField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FacultyModel',
        ),
        migrations.DeleteModel(
            name='ParentModel',
        ),
        migrations.DeleteModel(
            name='StudentFacultyCourses',
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
        migrations.DeleteModel(
            name='StudentParentRelation',
        ),
    ]
